services:
  - type: web
    name: youtube-to-mp3
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
    disk:
      name: downloads-storage
      mountPath: /app/downloads
      sizeGB: 1
